image: node:16

pipelines:
  default:
    - step:
        name: Build Vue.js Application
        caches:
          - node
        script:
          - npm install
          - npm run build
        artifacts:
          - dist/**

    - step:
        name: Deploy to IIS using Web Deploy
        deployment: production
        script:
          - apt-get update && apt-get install -y zip curl
          - zip -r vue-app.zip dist
          - curl -v -X POST "ufs-we-loadb-i5y4frjnejjx-1345884426.us-west-2.elb.amazonaws.com:8172/msdeploy.axd?site=apps.ba.arizona.edu" -u "$IIS_USERNAME:$IIS_PASSWORD" -H "MSDeploy-Path: /template" -H "Content-Type: application/zip" --upload-file vue-app.zip
