name: Build and move to beta site
run-name: ${{ github.event_name }} - ${{ github.actor }} - ${{ github.workflow }}

on:
  ## This is an example for pull requests being merged, see the if condition for event merged==true.
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - main
  #     - develop

  ## This is an example for a tagged release
  # release:
  #   types: [published]  

  ## This is just a simple push to main, we ideally would have a more robust git strategy here.
  push:
    # types: [closed]
    branches:
      - main

jobs:
  execute-beta-build-deploy:
    
    # If clause for pull_request being merged
    # if: ${{ github.event.pull_request.merged == true }}
    # If clause for a published release, major/minor version changes ala v1.0.0, 1.1, 2.0, etc.
    # if: ${{ github.event.release.tag_name =~ '^v[0-9]+\\.[0-9]+\\.0$' }}
    
    name: Execute Build / Beta Deploy
    runs-on: self-hosted
    # Or an example where we use labels to specify types of runners.
    # runs-on: [self-hosted, windows]
    environment: "daltont runner env"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Build Project
        run: |
          echo "Building project..."
          npm run build

      - name: Debug secrets
        run: |
          echo "Debugging secrets..."
          echo "Username: ${{ secrets.NETWORK_USERNAME }}"

      - name: Authenticate to Network Share (Beta)
        run: |
          net use \\bats-betawebapp3.bluecat.arizona.edu\inetpub\beta.apps.ba.arizona.edu /user:${{ secrets.NETWORK_USERNAME }} "${{ secrets.NETWORK_PASSWORD }}"

      - name: Move to beta site
        shell: pwsh
        run: |
          echo "Moving dist/ to beta site..."
          robocopy dist "\\bats-betawebapp3.bluecat.arizona.edu\inetpub\beta.apps.ba.arizona.edu\templateApp" /E /NFL /NDL /NJH /NJS /NC /NS
          if ($LASTEXITCODE -in 0, 1, 2, 3, 5, 6, 7) {
            exit 0
          } else {
            Write-Error "Robocopy failed with exit code $LASTEXITCODE"
            exit $LASTEXITCODE
          }