name: Build and move to beta site
run-name: ${{ github.event_name }} - ${{ github.actor }} - ${{ github.workflow }}

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  execute-beta-build-deploy:
    if: ${{ github.event.pull_request.merged == true }}
    name: Execute Build / Beta Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Build Project
        run: |
          echo "Building project..."
          npm run build

      - name: Move to beta site
        run: |
          echo "Moving dist/ to beta site..."
          npm run deploy:beta