name: Execute Tests on Pull Request

run-name: ${{ github.event_name }} - ${{ github.actor }} - ${{ github.workflow }}

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  Build Install and Test App:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Start dev server in the background
        run: |
          echo "Starting dev server..."
          npm run dev &
          echo $! > dev-server.pid

      - name: Wait for dev server to be ready
        run: |
          echo "Waiting for dev server to be ready..."
          npx wait-on http://localhost:3000 # Replace with your dev server URL

      - name: Run tests
        run: |
          echo "Running tests..."
          npm test

      - name: Stop dev server
        run: |
          echo "Stopping dev server..."
          kill $(cat dev-server.pid)