name: Execute Tests on Pull Request

run-name: ${{ github.event_name }} - ${{ github.actor }} - ${{ github.workflow }}

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  execute-tests-of-run-dev-server:
    name: Execute Tests of Run Dev Server
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Start dev server in the background
        shell: pwsh
        run: |
          echo "Starting dev server..."
          Start-Process -FilePath "npm" -ArgumentList "run dev" -NoNewWindow -RedirectStandardOutput "dev-server.log" -RedirectStandardError "dev-server.log" -PassThru | ForEach-Object { $_.Id } > dev-server.pid

      - name: Wait for dev server to be ready
        shell: pwsh
        run: |
          echo "Waiting for dev server to be ready..."
          npx wait-on http://localhost:8080

      - name: Stop dev server
        shell: pwsh
        run: |
          echo "Stopping dev server..."
          Stop-Process -Id (Get-Content dev-server.pid) -Force